local MSG_Common = {
    CrossRole = {
       roleId = 0,
       name = "",
       platform = "",
       serverId = 0,
       power = nil,
       career = nil,
    },
    ShowItemInfo = {
       modelId = 0,
       count = 0,
    },
    GroundBuffMess = {
       id = 0,
       modelId = 0,
       x = 0,
       y = 0,
       radius = 0,
       actType = 0,
    },
    Magic = {
       id = 0,
       modelId = "",
       x = 0,
       y = 0,
       delay = 0,
       radius = 0,
       ownerId = 0,
       moveSpeedFinal = 0,
    },
    BonfireInfo = {
       id = 0,
       bonfireId = 0,
       modelId = 0,
       x = 0,
       y = 0,
    },
    TombstoneInfo = {
       id = 0,
       stoneId = 0,
       x = 0,
       y = 0,
       cd = 0,
    },
    Buff = {
       buffId = 0,
       curLevel = 0,
       remainTime = 0,
       args = List:New(),
    },
    Position = {
       x = 0,
       y = 0,
    },
    PlayerInfo = {
       playerId = 0,
       name = "",
       career = 0,
       level = 0,
       x = 0,
       y = 0,
       curHp = 0,
       maxHp = 0,
       moveSpeedFinal = 0,
       attackSpeedFinal = 0,
       mountId = nil,
       guildId = nil,
       guildName = nil,
       guildPost = nil,
       posList = List:New(),
       buffList = List:New(),
       title = 0,
       dirX = 0,
       dirY = 0,
       isGather = false,
       marriageOtherName = nil,
       stateVip = 0,
       onSitting = false,
       camp = 0,
       fabaoId = nil,
       fabaoUid = nil,
       soulSpirte1 = 0,
       soulSpirte2 = 0,
       soulSpirte3 = 0,
       shiHaiCfgId = 0,
       serverId = nil,
       curWakan = nil,
       maxWakan = nil,
       facade = {
            fashionBody = nil,
            fashionWeapon = nil,
            fashionHalo = nil,
            fashionMatrix = nil,
            wingId = nil,
            spiritId = nil,
            soulArmorId = nil,
        },

       fightState = 0,
       feijianId = nil,
       feijianUid = nil,
       childId = nil,
       fightPower = nil,
       head = nil,
       childName = nil,
       taskList = List:New(),
       stateAnimFinal = nil,
       pointSatKhi = nil,
       pointLinhKhi = nil,
       prisonNameId = nil,
    },
    NameAttribute = {
       typeAttr = nil,
       nameAttr = nil,
    },
    MonsterInfo = {
       id = 0,
       dataID = 0,
       camp = nil,
       x = 0,
       y = 0,
       curHp = 0,
       maxHp = 0,
       moveSpeedFinal = 0,
       attackSpeedFinal = 0,
       fightState = 0,
       posList = List:New(),
       buffList = List:New(),
       dirX = 0,
       dirY = 0,
       isRun = false,
       isbirth = nil,
       armor = nil,
       dropUserIds = List:New(),
       nameList = List:New(),
    },
    PetInfo = {
       id = 0,
       dataID = 0,
       ownerID = 0,
       ownerName = "",
       x = 0,
       y = 0,
       speed = 0,
       posList = List:New(),
       level = nil,
       camp = nil,
       curHp = 0,
       maxHp = 0,
       fightState = 0,
       buffList = List:New(),
    },
    NpcInfo = {
       npcId = 0,
       dataID = 0,
       x = 0,
       y = 0,
       dir = nil,
    },
    GatherInfo = {
       gatherId = 0,
       dataID = 0,
       mapId = 0,
       x = 0,
       y = 0,
    },
    NearPlayerInfo = {
       memberId = 0,
       memberName = "",
       memberLv = 0,
       memberFighting = 0,
       memberMapId = 0,
       memberLine = 0,
       career = 0,
       haveTeam = false,
       mrank = nil,
    },
    FuzzyQueryList = {
       memberId = 0,
       memberName = "",
       memberLv = 0,
       memberFighting = 0,
       memberMapId = 0,
       memberLine = 0,
       career = 0,
       haveTeam = false,
    },
    ApplyInfo = {
       roleId = 0,
       lv = 0,
       name = "",
       sex = 0,
       guildId = 0,
       guildName = "",
    },
    powerAttribute = {
       type = 0,
       value = 0,
    },
    CrossAttribute = {
       type = nil,
       value = nil,
       param = nil,
       param1 = nil,
    },
    FacadeAttribute = {
       fashionBody = nil,
       fashionWeapon = nil,
       fashionHalo = nil,
       fashionMatrix = nil,
       wingId = nil,
       spiritId = nil,
       soulArmorId = nil,
    },
    HeadAttribute = {
       fashionHead = nil,
       fashionFrame = nil,
       customHeadPath = nil,
       useCustomHead = nil,
    },
    KeyValueInfo = {
       key = "",
       value = "",
    },
    TaskListInfo = {
       taskType = nil,
       taskModelId = nil,
       taskUid = nil,
    },
    gemPartInfo = {
       gemIds = List:New(),
       jadeIds = List:New(),
       level = 0,
       exp = 0,
    },
    EquipWashInfo = {
       index = 0,
       per = 0,
       value = 0,
       poolId = 0,
    },
    EquipStrengthInfo = {
       type = 0,
       level = 0,
       exp = 0,
    },
    ItemInfo = {
       itemId = 0,
       itemModelId = 0,
       num = 0,
       gridId = nil,
       isbind = nil,
       lostTime = nil,
       cdTime = nil,
       suitId = nil,
       strengLv = nil,
       percent = nil,
    },
    EquipPartInfo = {
       type = 0,
       washInfo = List:New(),
       strengthInfo = nil,
       gemInfo = nil,
       equip = nil,
       raisalInfo = List:New(),
       attrSpecial = List:New(),
    },
    EquipPartInfoBags = {
       itemId = 0,
       info = nil,
    },
}
local L_StrDic = {
}
local L_SendDic = setmetatable({},{__mode = "k"});

local mt = {}
mt.__index = mt
function mt:New()
    local _str = L_StrDic[self]
    local _clone = Utils.DeepCopy(self)
    L_SendDic[_clone] = _str
    return _clone
end
function mt:Send()
    GameCenter.Network.Send(L_SendDic[self], self)
end

for k,v in pairs(L_StrDic) do
    setmetatable(k, mt)
end

return MSG_Common

