local M = {
    -- Record the GUID generated by the current map custom icon
    GenGUID = 0,
    -- Custom object dictionary
    CustomIdDic = Dictionary:New(),
    CustomTypeDic = Dictionary:New(),
}

function M:Initialize()
    self.GenGUID = 0;
    self.CustomIdDic:Clear();
    self.CustomTypeDic:Clear();
end

function M:UnInitialize()
    
end

-- Get the unique ID generated by the map custom icon
function M:GetGUID()
    self.GenGUID = self.GenGUID + 1;
    return self.GenGUID;
end

-- Add custom object [customType: MapCustomType]
function M:AddObject(customType, name, worldPosX, worldPosZ)
    local _guid = self:GetGUID();
    local _data = {Id = _guid, CustomType = customType, Name = name or "", WorldPosX = worldPosX, WorldPosZ = worldPosZ};
    self.CustomIdDic:Add(_guid, _data);
    if not self.CustomTypeDic:ContainsKey(customType) then
        self.CustomTypeDic:Add(customType, Dictionary:New());
    end
    self.CustomTypeDic[customType]:Add(_guid, _data)
    GameCenter.PushFixEvent(LogicLuaEventDefine.EID_EVENT_MAP_CUSTOMOBJECT_REFESH);
    return _guid;
end

-- Set the location
function M:SetPos(id, worldPosX, worldPosZ)
    local _customObj = self.CustomIdDic[id];
    if _customObj then
        _customObj.WorldPosX = worldPosX;
        _customObj.WorldPosZ = worldPosZ;
        GameCenter.PushFixEvent(LogicLuaEventDefine.EID_EVENT_MAP_CUSTOMOBJECT_REFESH);
    end
end

-- Change the name
function M:ChangeName(id, name)
    local _customObj = self.CustomIdDic[id];
    if _customObj then
        _customObj.Name = name or "";
        GameCenter.PushFixEvent(LogicLuaEventDefine.EID_EVENT_MAP_CUSTOMOBJECT_REFESH);
    end
end

-- Remove custom objects
function M:RemoveObject(id)
    local _data = self.CustomIdDic[id];
    if _data then
        self.CustomIdDic:Remove(id);
        self.CustomTypeDic[_data.CustomType]:Remove(id)
        GameCenter.PushFixEvent(LogicLuaEventDefine.EID_EVENT_MAP_CUSTOMOBJECT_REFESH);
    end
end

-- Remove custom objects by type
function M:RemoveObjectByType()
    --TODO
    GameCenter.PushFixEvent(LogicLuaEventDefine.EID_EVENT_MAP_CUSTOMOBJECT_REFESH);
end

-- Remove all custom objects
function M:ClearObject()
    self.CustomIdDic:Clear();
    self.CustomTypeDic:Clear();
    GameCenter.PushFixEvent(LogicLuaEventDefine.EID_EVENT_MAP_CUSTOMOBJECT_REFESH);
end

return M